In [ ]:
n1=[1,2,3,4]
n2=[11,12,13]
print(n1+n2)

[1, 2, 3, 4, 11, 12, 13]


In [ ]:
#a1[index]
import numpy as np
a1 = np.array([1,2,3,4])
a2 = np.array([5,4,8,10])
#a1+a2
print(a1.ndim) 

1


In [ ]:
#arr2[row,col]
arr2 = np.array( [  [11,12,13],  [21,22,23], [31,32,33], [41,42,43]])
#print(arr2.ndim)
#print(arr2.shape)
#print(arr2.dtype)
arr2 = arr2.reshape((2,6))
#print(arr2.size)



In [ ]:
arr3 = np.array([   [[11,12],[21,22],[31,32]]   ,
          [[101,102],[201,202],[301,302]], 
          [[911,912],[921,922],[931,932]] ])

arr3
#arr3[sheet,row,col]
#arr3[2,2,0]


In [ ]:
#arr2[row,col]
arr2[:,1:3]


In [ ]:
arr3 = np.array([   [[11,12],[21,22],[31,32]]   ,
          [[101,102],[201,202],[301,302]], 
          [[911,912],[921,922],[931,932]] ])

arr3
#arr3[sheet,row,col]
#arr3[2,2,0]


In [ ]:
#empty arrays --np.zeros(),np.ones()
#pre-filled arrays --np.full()
#random generated arrays

In [ ]:
arr = np.random.randn(5,5)
#arr = np.ones((3,6))
#arr
emp_arr = np.full((3,6),99)
emp_arr

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [ ]:
print(arr)

[[-1.16753846 -0.8171751  -0.51241955 -0.15182479 -0.21038679]
 [ 0.24383611  1.13041993 -1.10182474 -0.40070938 -1.38069524]
 [ 0.04161164  0.58989867  0.22290571 -0.72747966 -0.93748214]
 [ 0.37755158  0.74716451 -0.01616404  0.65076385  1.81127422]
 [ 1.56778222  1.40752326 -1.60250924 -1.6008307   0.04355021]]


In [ ]:
                  
#adding row to the existing dataframe--contact
#
df3 = pd.DataFrame({
    'Name':['khitij','sania','karan','arjun','mahek'],
    'Age':[23,24,25,62,45],
    'Dept':['h','a','s','i','h']
}, index=np.arange(801,806))
print(df3)

       Name  Age Dept
801  khitij   23    h
802   sania   24    a
803   karan   25    s
804   arjun   62    i
805   mahek   45    h


In [ ]:
df4 =pd.DataFrame({
    'EmpCode':[801,802,806,811],
    'Location':['Thane','Andheri','Thane','Andheri'],
    'Project':['RailYatra','Metro','RailYatra','Metro'],
    
}, index=[801,802,806,811])
print(df4)
print(df3)
# adding rows to the existing dataframe -- concat
# multiple dataframes having some common column --  merge
df3 = pd.DataFrame({
    'EmpCode':np.arange(801,806),
    'Name':['Khitij','Sania','Karan','Arjun','Mehek'],
    'Age':[23,34,42,35,56],
    'dept':['H','A','S','I','H']
}, index=np.arange(801,806))
print(df3)

In [ ]:
ne = pd.DataFrame({'Empcode': '811',
                  'Name': 'NIKITA',
                  'Age':34,                 
                  'dept':'H'}, index=[811])

In [ ]:
ne = pd.DataFrame({'EmpCode':811,
    'Name':'Zeeshan',
    'Age':34,
    'dept':'H'}, index=[811])
df3 = pd.concat([df3,ne],axis=0)
pd.concat([df3,df4],axis=1)
final = df3.merge(df4,how="outer")
top_2 = final.sort_values(by="Age", ascending=False).head(2)

In [ ]:
import pandas as pd
s1 = pd.Series([23,24,45,67],index=[1,2,3,4])
s2 = pd.Series([23,24,45,67],index=[1,2,4,5])

df = pd.DataFrame( index=[1,2,3,4,5,6])
df['Maths'] = s1
df['Physics'] = s2
print(df)

   Maths  Physics
1   23.0     23.0
2   24.0     24.0
3   45.0      NaN
4   67.0     45.0
5    NaN     67.0
6    NaN      NaN


In [ ]:
import numpy as np
a1 = np.array([23,24,45,67])
a2 = np.array([23,24,45,67])
df1 = pd.DataFrame()
df1['Maths'] = a1
df1['Physics'] = a2
print(df1)

   Maths  Physics
0     23       23
1     24       24
2     45       45
3     67       67


In [ ]:
df2 = pd.DataFrame(columns=['Name','Dept','Salary'], index=[801,802,803,804])
print(df2)

    Name Dept Salary
801  NaN  NaN    NaN
802  NaN  NaN    NaN
803  NaN  NaN    NaN
804  NaN  NaN    NaN


In [ ]:
gy = pd.DataFrame({
    'Name':['chola','mazza','real','tropicana','frutie'],
    'Prserno':[2153,1254,4587,1011,1555],
     'Price':[20,50,30,40,10],
     'Qty':[100,200,500,300,420]
}, index=np.arange(50,55))
print(gy)


         Name  Prserno  Price  Qty
50      chola     2153     20  100
51      mazza     1254     50  200
52       real     4587     30  500
53  tropicana     1011     40  300
54     frutie     1555     10  420


In [ ]:
gy.columns

Index(['Name', 'Prserno', 'Price', 'Qty'], dtype='object')

In [ ]:
 gy.index

Int64Index([50, 51, 52, 53, 54], dtype='int64')

In [ ]:
 gy['Qty']

50    100
51    200
52    500
53    300
54    420
Name: Qty, dtype: int64

In [ ]:
gy.iloc[0]

Name       chola
Prserno     2153
Price         20
Qty          100
Name: 50, dtype: object

In [ ]:
gy.iloc[[0,4]]

Name  Prserno  Price  Qty
50   chola     2153     20  100
54  frutie     1555     10  420

In [ ]:
gy['Name'].loc[52]='fanta'
gy

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


Name  Prserno  Price  Qty
50      chola     2153     20  100
51      mazza     1254     50  200
52      fanta     4587     30  500
53  tropicana     1011     40  300
54     frutie     1555     10  420

In [ ]:
gy[['Name','Prserno']].loc[[51,52,53]]

Name  Prserno
51      mazza     1254
52       real     4587
53  tropicana     1011

In [ ]:
gy.loc[52]

Name       real
Prserno    4587
Price        30
Qty         500
Name: 52, dtype: object

In [ ]:
df3 = pd.DataFrame({
    'Name':['khitij','sania','karan','arjun','mahek'],
    'Age':[23,24,25,62,45],
    'Dept':['h','a','s','i','h']
}, index=np.arange(801,806))
print(df3)

       Name  Age Dept
801  khitij   23    h
802   sania   24    a
803   karan   25    s
804   arjun   62    i
805   mahek   45    h


In [ ]:
df3['Location']=pd.Series(['thane','mulund','thane','vilkhroli'])
print(df3)

       Name  Age Dept Location
811  khitij   23    h      NaN
802   sania   24    a      NaN
803   karan   25    s      NaN
804   arjun   62    i      NaN
805   mahek   45    h      NaN


In [ ]:
#Deleting the columns and row
df3.drop('Dept', axis=1, inplace=True)

In [ ]:
df3['Salary']=np.NaN
df3

Name  Age Location  Salary
811  khitij   23      NaN     NaN
802   sania   24      NaN     NaN
803   karan   25      NaN     NaN
804   arjun   62      NaN     NaN
805   mahek   45      NaN     NaN

In [ ]:
df3.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       Name    Age  Location  Salary
811  False  False      True    True
802  False  False      True    True
803  False  False      True    True
804  False  False      True    True
805  False  False      True    True>

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 811 to 805
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      5 non-null      object 
 1   Age       5 non-null      int64  
 2   Location  0 non-null      object 
 3   Salary    0 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 200.0+ bytes


In [ ]:
df3.isnull().sum()

Name        0
Age         0
Location    5
Salary      5
dtype: int64

In [ ]:
df3.isnull().sum()

Name        0
Age         0
Location    5
Salary      5
dtype: int64

In [ ]:
#rename the row
df3.rename({801:811},axis=0, inplace=True)

In [ ]:
df3.columns

Index(['Name', 'Age', 'Dept', 'Location'], dtype='object')

In [ ]:
df3.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#missing value traatment -- deleted, fill
df3['Salary'].iloc[0]=23000
df3


/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


Name  Age Location   Salary
811  khitij   23      NaN  23000.0
802   sania   24      NaN      NaN
803   karan   25      NaN      NaN
804   arjun   62      NaN      NaN
805   mahek   45      NaN      NaN

In [ ]:
df3['Salary'].iloc[3]=50000
df3

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


Name  Age Location   Salary
811  khitij   23      NaN  23000.0
802   sania   24      NaN      NaN
803   karan   25      NaN      NaN
804   arjun   62      NaN  50000.0
805   mahek   45      NaN      NaN

In [ ]:
df3.dropna()#droping all the row where null value are presents
df3['Location'].dropna()

Series([], Name: Location, dtype: object)

In [ ]:
#filling the missing valuses
df3['Location'].fillna('alpha')

811    alpha
802    alpha
803    alpha
804    alpha
805    alpha
Name: Location, dtype: object

In [ ]:
df3['Salary'].fillna(df3['Salary'].mean())

811    23000.0
802    36500.0
803    36500.0
804    50000.0
805    36500.0
Name: Salary, dtype: float64

In [ ]:
df3['Location'].fillna(method='bfill')#ffill \bfill both opthion we can use

811   NaN
802   NaN
803   NaN
804   NaN
805   NaN
Name: Location, dtype: float64

In [ ]:
#statistical functions
df3.describe()

Age        Salary
count   5.000000      2.000000
mean   35.800000  36500.000000
std    17.253985  19091.883092
min    23.000000  23000.000000
25%    24.000000  29750.000000
50%    25.000000  36500.000000
75%    45.000000  43250.000000
max    62.000000  50000.000000

In [ ]:
df3['Age'].count()
df3['Age'].mean()
df3['Age'].std()
df3['Age'].max()
df3['Age'].min()
df3['Age'].sum()
df3['Age'].var()

297.7

In [ ]:
df3.head(2)
df3.tail(2)

Name  Age Location   Salary
804  arjun   62      NaN  50000.0
805  mahek   45      NaN      NaN

In [ ]:
import pandas as pd
import numpy as np

mt = pd.read_csv("mtcars.csv")

In [ ]:
gg_mpg = mt.groupby('carb')

avg_mpg=[]
carb=[]

for g in mt['carb'].unique():
  carb.append(g)
  avg_mpg.append(gg_mpg.get_group(g)['mpg'].mean())

print(carb)
print(avg_mpg)
plt.pie(avg_mpg, labels=avg_mpg )

In [ ]:
mt['carb'].unique()

array([4, 1, 2, 3, 6, 8])

In [ ]:
mt['carb'].unique()

array([4, 1, 2, 3, 6, 8])

In [ ]:
plt.pie(mt['carb'].value_counts())

In [ ]:
mt.info()

In [ ]:
mt.head()

In [ ]:
mt.rename({"model":"car_name"},axis=1,inplace=True)

In [ ]:
mt['gear'].unique()
#mt['carb'].unique()
#mt['cyl'].unique()

In [ ]:
mt['gear'].value_counts() \ # mt['gear'].counts()

In [ ]:
#comdition = mt['gear']==5
mt[ (mt["gear"] ==5) & (mt["carb"]>5)].count()
#mt['gear'] == 5
#average mileage of cars having gear==5 and carb>5

car_name   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29   Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8

In [ ]:
#average hp of cars having milege >22
mt[mt['mpg']>22]['hp'].mean()

78.11111111111111

In [ ]:
#min disp of cars having am =0
#no. of cars having am=0,am=1
mt['am'].value_counts()

0    19
1    13
Name: am, dtype: int64

In [ ]:
pd.crosstab(mt['gear'],mt['cyl'])

cyl   4  6   8
gear          
3     1  2  12
4     8  4   0
5     2  1   2

In [ ]:
gg_gear = mt.groupby('gear')

In [ ]:
gg_gear.get_group(5)['mpg'].mean()

21.380000000000003

In [ ]:
for g in mt['gear'].unique():
  print(g,gg_gear.get_group(g)['mpg'].mean())

4 24.53333333333333
3 16.106666666666666
5 21.380000000000003


In [ ]:
gg_gcyl = mt.groupby(['gear','cyl'])